export const mockData1 = {
  query_path: {
    path: '/api/schedule/joinGroup',
    params: [],
  },
  edit_uid: 0,
  status: 'undone',
  type: 'static',
  req_body_is_json_schema: false,
  res_body_is_json_schema: false,
  api_opened: false,
  index: 0,
  tag: [],
  _id: 204670,
  method: 'GET',
  catid: 20023,
  title: '加入日程群聊',
  path: '/api/schedule/joinGroup',
  project_id: 179,
  req_params: [],
  res_body_type: 'json',
  req_query: [
    {
      required: '1',
      _id: '6172324124c2583c3196e829',
      name: 'scheduleId',
      example: '1231231',
      desc: '日程id',
    },
  ],
  req_body_other: '{"type":"object","title":"empty object","properties":{"calendarId":{"type":"number","description":"日程ID"},"targetDate":{"type":"string","description":"日程日期"}},"required":["calendarId","targetDate"]}',
  req_headers: [],
  req_body_form: [],
  desc: '',
  markdown: '',
  res_body:
    '{\n    "code":0, // 状态码。0表示成功，其他表示错误\n    "msg":"", // 状态信息\n    "data":{ // 接口返回数据\n        "groupIdEnc": "xxxxxxx", // 加密群id\n        "groupName":"吃饭群", // 群名称\n        "groupNamePy":"chi fan qun", // 群名称拼音\n        "avatar":"http........png", // 群头像url\n        "tinyAvatar":"http.....png", // 缩略头像链接\n        "bulletin":"群公告：好好学习，天天向上", // 群公告\n        "bulletinUpdateUid": 1551665155012, // 群公告更新用户id，可空\n        "bulletinUpdateTs": 1551665155012, // 群公告更新时间，可空\n        "ownerAtAll": 1, // 开启只有群主能@所有人，0-不开启，1-开启\n        "ownerAddUser": 0, // 开启只有群主能添加用户，0-不开启，1-开启\n        "ownerEdit": 1, // 开启只有群主能编辑群信息，0-不开启，1-开启\n        "top":1, // 置顶设置:0-不置顶，1-置顶\n        "silence":0, // 免打扰设置:0-不免，1-免\n        "status":0, // 状态：0-正常，1-解散\n        "type": 1, // 群组类型，1-普通群，2-项目组\n        "users":[{\n            "userId":20000001, // 用户id\n            "nickName":"李一", // 群昵称，可空\n            "nickNamePy":"li yi", // 群昵称拼音，可空\n            "status":1 // 用户状态：0-正常，1-退群，2-踢出\n        },{\n            "userId":20000001, // 用户id\n            "nickName":"", // 群昵称，可空\n            "nickNamePy":"", // 群昵称拼音，可空\n            "status":1 // 用户状态：0-正常，1-退群，2-踢出\n        }]\n    }\n}',
  uid: 2060,
  add_time: 1628132769,
  up_time: 1634873921,
  __v: 0,
  username: '姬帅',
};

export const mockData2 = {
  query_path: {
    path: '/api/calendar/test',
    params: [],
  },
  edit_uid: 0,
  status: 'done',
  type: 'static',
  req_body_is_json_schema: true,
  res_body_is_json_schema: true,
  api_opened: false,
  index: 0,
  tag: [],
  _id: 422171,
  method: 'POST',
  catid: 20023,
  title: '代码自动生成测试',
  path: '/api/calendar/test',
  project_id: 179,
  req_params: [],
  res_body_type: 'json',
  uid: 6443,
  add_time: 1662176048,
  up_time: 1662553289,
  req_query: [],
  req_headers: [
    {
      required: '1',
      _id: '63188cc9b2e15d2206a7f520',
      name: 'Content-Type',
      value: 'application/json',
    },
  ],
  req_body_form: [
    {
      required: '1',
      _id: '63188cc9b2e15d2206a7f522',
      name: 'calendarId',
      type: 'text',
    },
    {
      required: '1',
      _id: '63188cc9b2e15d2206a7f521',
      name: 'targetDate',
      type: 'text',
      example: '',
      desc: '',
    },
  ],
  __v: 0,
  desc: '',
  markdown: '',
  req_body_type: 'json',
  res_body:
    '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"code":{"type":"number","description":"状态码","mock":{"mock":"@string"}},"msg":{"type":"string","description":"错误信息","mock":{"mock":"@string"}},"data":{"type":"object","properties":{"version":{"type":"number","description":"版本号","mock":{"mock":"@lower"}},"subVersion":{"type":"number","description":"子版本号","mock":{"mock":"@natural"}},"hasMore":{"type":"number","description":"是否有更多","mock":{"mock":"@natural"}},"extraData":{"type":"object","properties":{"type":{"type":"string","description":"类型"},"value":{"type":"string","description":"数值"}},"description":"额外属性","required":["type","value"]},"status":{"type":"string","description":"状态, success-成功，pending-待定，error-错误","enum":["success","pending","error"]},"userList":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string","description":"姓名"},"age":{"type":"string"}},"required":["name","age"],"description":"用户项"},"description":"用户列表"}},"description":"返回数据","required":["extraData","status"]}},"required":["code","msg","data"]}',
  req_body_other: '{"type":"object","title":"empty object","properties":{"calendarId":{"type":"number","description":"日程ID"},"targetDate":{"type":"string","description":"日程日期"}},"required":["calendarId","targetDate"]}',
  username: '周非凡',
};
